# Generated by Django 3.0.8 on 2020-07-29 13:43

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0005_auto_20200729_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, max_length=200, null=''),
        ),
    ]
