# Generated by Django 3.0.8 on 2020-08-08 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0010_auto_20200808_1548'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='object_id',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='parent',
        ),
    ]
